# Generated by Django 5.0.14 on 2026-06-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_patrimonio', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('especificacao_tecnica', models.TextField(blank=True, null=True)),
                ('etiquetado', models.BooleanField(default=False)),
                ('categoria', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Novo', 'Novo'), ('Em_Uso', 'Em Uso'), ('Em_Manutencao', 'Em Manutenção'), ('Baixado', 'Baixado'), ('Disponivel', 'Disponível'), ('Emprestado', 'Emprestado')], default='Novo', max_length=50)),
                ('elegivel_emprestimo', models.BooleanField(default=False)),
                ('imagem_url', models.TextField(blank=True, null=True)),
                ('storage_key', models.TextField(blank=True, null=True)),
                ('especificacoes_tecnicas', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'db_table': 'ativos',
            },
        ),
        migrations.CreateModel(
            name='InstalacaoSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_instalacao', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instalação de Software',
                'verbose_name_plural': 'Instalações de Softwares',
                'db_table': 'instalacoes_software',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('Novo', 'Novo'), ('Em_Uso', 'Em Uso'), ('Em_Manutencao', 'Em Manutenção'), ('Baixado', 'Baixado'), ('Disponivel', 'Disponível'), ('Emprestado', 'Emprestado')], max_length=50, null=True)),
                ('status_novo', models.CharField(choices=[('Novo', 'Novo'), ('Em_Uso', 'Em Uso'), ('Em_Manutencao', 'Em Manutenção'), ('Baixado', 'Baixado'), ('Disponivel', 'Disponível'), ('Emprestado', 'Emprestado')], max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimentação de Ativo',
                'verbose_name_plural': 'Movimentações de Ativos',
                'db_table': 'movimentacoes_ativo',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
                ('total_licencas_compradas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
                'db_table': 'softwares',
            },
        ),
        migrations.CreateModel(
            name='AtivoTI',
            fields=[
                ('ativo', models.OneToOneField(db_column='ativo_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ti_profile', serialize=False, to='ativos.ativo')),
                ('marca', models.CharField(max_length=100)),
                ('memoria_ram_gb', models.SmallIntegerField(blank=True, null=True)),
                ('armazenamento_gb', models.IntegerField(blank=True, null=True)),
                ('sistema_operacional', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ativo de TI',
                'verbose_name_plural': 'Ativos de TI',
                'db_table': 'ativos_ti',
            },
        ),
    ]
