# Generated by Django 5.0.14 on 2026-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Iniciacao_Cientifica', 'Iniciação Científica'), ('Monitoria', 'Monitoria'), ('Estagio', 'Estágio'), ('Extensao', 'Extensão')], max_length=50)),
                ('status', models.CharField(choices=[('Em_Andamento', 'Em Andamento'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Em_Andamento', max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Atividade Acadêmica',
                'verbose_name_plural': 'Atividades Acadêmicas',
                'db_table': 'atividades_academicas',
            },
        ),
    ]
