# Generated by Django 5.0.14 on 2026-06-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeacademica',
            name='aluno',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, related_name='atividades_academicas', to='usuarios.aluno'),
        ),
    ]
