# Generated by Django 5.0.14 on 2026-06-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeacademica',
            name='status',
            field=models.CharField(choices=[('Em_Andamento', 'Em Andamento'), ('Concluida', 'Concluída'), ('Cancelada', 'Cancelada')], default='Em_Andamento', max_length=50),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='tipo',
            field=models.CharField(choices=[('Estagio_Obrigatorio', 'Estágio Obrigatório'), ('Estagio_Nao_Obrigatorio', 'Estágio Não Obrigatório'), ('PIBIC', 'PIBIC — Programa Institucional de Bolsas de Iniciação Científica'), ('PIVIC', 'PIVIC — Programa de Iniciação Científica Voluntária'), ('Extensao', 'Extensão'), ('Monitoria', 'Monitoria'), ('Trabalho_Academico', 'Trabalho Acadêmico'), ('PIBID', 'PIBID — Programa Institucional de Bolsa de Iniciação à Docência'), ('Empresa_Junior', 'Empresa Júnior'), ('Publicacao_Cientifica', 'Publicação Científica'), ('Organizacao_Evento', 'Organização de Evento'), ('Atividade_Cultural_Esportiva', 'Atividade Cultural/Esportiva')], max_length=50),
        ),
    ]
