# Generated by Django 5.0.14 on 2026-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_alter_atividadeacademica_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeacademica',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividadeacademica',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
