# Generated by Django 5.0.14 on 2026-06-23 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='autorizado_por',
            field=models.ForeignKey(db_column='autorizado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_autorizados', to='usuarios.servidor'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
