# Generated by Django 5.0.14 on 2026-06-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='tipo',
            field=models.CharField(choices=[('Conselhos_Superiores', 'Conselhos Superiores (CONSUNI/CONSEPE/CADFUnDF)'), ('Reitoria', 'Reitoria'), ('Vice_Reitoria', 'Vice-Reitoria'), ('Procuradoria_Juridica', 'Procuradoria Jurídica (PROJUR)'), ('Controladoria_Setorial', 'Controladoria Setorial'), ('Ouvidoria', 'Ouvidoria'), ('Biblioteca_Central', 'Biblioteca Central (BCE)'), ('Agencia_de_Comunicacao', 'Agência de Comunicação (ASCOM)'), ('Secretaria_Academica_Geral', 'Secretaria Acadêmica Geral (SEAG)'), ('Secretaria_Executiva', 'Secretaria Executiva (SECEX)'), ('Unidade_Planejamento_Orcamento_Gestao', 'Unid. Planejamento, Orçamento e Gestão (UPOG)'), ('Unidade_Escritorio_de_Negocios', 'Unidade Escritório de Negócios (UEN)'), ('Prefeitura_Universitaria', 'Prefeitura Universitária'), ('PRODRS', 'Pró-Reitoria de Desenvolvimento Regional e Sustentável'), ('PRODUNI', 'Pró-Reitoria de Desenvolvimento Universitário'), ('PROEXTC', 'Pró-Reitoria de Extensão e Cultura'), ('PROGRAD', 'Pró-Reitoria de Graduação'), ('PROPPG', 'Pró-Reitoria de Pesquisa e Pós-Graduação'), ('UAG', 'Unidade de Administração Geral'), ('UAG_Patrimonio', 'UAG — Diretoria de Patrimônio, Recursos Materiais e Serviços'), ('UAG_Contratos', 'UAG — Diretoria de Contratos e Convênios'), ('UAG_Financeiro', 'UAG — Diretoria de Contabilidade, Orçamento e Finanças'), ('UAG_Gestao_Pessoas', 'UAG — Diretoria de Gestão de Pessoas'), ('UAG_Compras', 'UAG — Diretoria de Gestão de Compras'), ('UAG_Arquivo', 'UAG — Gerência de Arquivo, Protocolo e Documentos'), ('Ceinter_Ciencias_Humanas', 'Ceinter de Ciências Humanas (COCHCMA)'), ('Ceinter_Educacao_Artes', 'Ceinter de Educação e Artes (COEMAG)'), ('Ceinter_Engenharia_TI', 'Ceinter de Engenharia e TI (COETI)'), ('Ceinter_Ciencias_Saude', 'Ceinter de Ciências da Saúde (COCBS)'), ('TI_Campus', 'TI do Campus (Suporte Técnico Local)'), ('Secretaria_Campus', 'Secretaria Acadêmica do Campus'), ('Coordenacao_Curso', 'Coordenação de Curso'), ('Laboratorio', 'Laboratório Acadêmico'), ('Biblioteca_Setorial', 'Biblioteca Setorial'), ('Almoxarifado', 'Almoxarifado do Campus')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('escola', 'campus', 'nome'), name='uq_curso_escola_campus_nome'),
        ),
        migrations.AddConstraint(
            model_name='setor',
            constraint=models.UniqueConstraint(fields=('campus', 'tipo'), name='uq_setores_campus_tipo'),
        ),
    ]
