# Generated by Django 5.0.14 on 2026-06-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_alter_setor_tipo_curso_uq_curso_escola_campus_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
