# Generated by Django 5.0.14 on 2026-07-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0003_campus_ativo_curso_ativo_escola_ativo_setor_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Sala', 'Sala'), ('Laboratorio', 'Laboratório')], max_length=50)),
                ('campus', models.ForeignKey(db_column='campus_id', on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='instituicao.campus')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'salas',
            },
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(fields=('campus', 'numero'), name='uq_salas_campus_numero'),
        ),
    ]
