# Generated by Django 5.0.14 on 2026-06-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateTimeField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('status_conservacao_retorno', models.CharField(blank=True, choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Regular', 'Regular'), ('Danificado', 'Danificado')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Devolvido', 'Devolvido'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Ativo', max_length=50)),
                ('observacao_saida', models.TextField(blank=True, null=True)),
                ('observacao_devolucao', models.TextField(blank=True, null=True)),
                ('ativo', models.ForeignKey(db_column='ativo_id', on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='ativos.ativo')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'db_table': 'emprestimos',
            },
        ),
    ]
