# Generated by Django 5.0.14 on 2026-06-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Concluido', 'Concluído'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Ativo', max_length=50),
        ),
    ]
