# Generated by Django 5.0.14 on 2026-07-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_emprestimo_status'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, db_column='autorizado_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_autorizados', to='usuarios.servidor'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Concluido', 'Concluído'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50),
        ),
    ]
