# Generated by Django 5.0.14 on 2026-07-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_add_enum_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Concluido', 'Concluído'), ('Atrasado', 'Atrasado'), ('Finalizado', 'Finalizado')], default='Pendente', max_length=50),
        ),
    ]
