# Generated by Django 5.0.14 on 2026-07-11 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_ativoti_sala_solicitacaoinstalacao'),
        ('emprestimos', '0006_alter_emprestimo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(db_column='ativo_id', on_delete=django.db.models.deletion.CASCADE, related_name='fila_espera', to='ativos.ativo')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='filas_espera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fila de Empréstimo',
                'verbose_name_plural': 'Filas de Empréstimo',
                'db_table': 'filas_emprestimo',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='filaemprestimo',
            constraint=models.UniqueConstraint(fields=('ativo', 'usuario'), name='uq_fila_ativo_usuario'),
        ),
    ]
