# Generated by Django 5.0.14 on 2026-06-23 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
        ('instituicao', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='responsavel',
            field=models.ForeignKey(db_column='responsavel_id', on_delete=django.db.models.deletion.PROTECT, related_name='ativos_responsaveis', to='usuarios.servidor'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='setor',
            field=models.ForeignKey(db_column='setor_id', on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='instituicao.setor'),
        ),
        migrations.AddField(
            model_name='movimentacaoativo',
            name='ativo',
            field=models.ForeignKey(db_column='ativo_id', on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ativos.ativo'),
        ),
        migrations.AddField(
            model_name='movimentacaoativo',
            name='operador',
            field=models.ForeignKey(db_column='operador_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_operadas', to='usuarios.servidor'),
        ),
        migrations.AddField(
            model_name='movimentacaoativo',
            name='setor',
            field=models.ForeignKey(db_column='setor_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_recebidas', to='instituicao.setor'),
        ),
        migrations.AddField(
            model_name='instalacaosoftware',
            name='software',
            field=models.ForeignKey(db_column='software_id', on_delete=django.db.models.deletion.CASCADE, related_name='instalacoes', to='ativos.software'),
        ),
        migrations.AddField(
            model_name='instalacaosoftware',
            name='ativo_ti',
            field=models.ForeignKey(db_column='ativo_ti_id', on_delete=django.db.models.deletion.CASCADE, related_name='instalacoes_software', to='ativos.ativoti'),
        ),
    ]
