# Generated by Django 5.0.14 on 2026-06-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='especificacoes_tecnicas',
        ),
        migrations.AlterField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Avariado', 'Avariado'), ('Desempossado', 'Desempossado'), ('Emprestado', 'Emprestado'), ('Em_Uso', 'Em Uso'), ('Disponivel', 'Disponível')], default='Novo', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimentacaoativo',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('Novo', 'Novo'), ('Avariado', 'Avariado'), ('Desempossado', 'Desempossado'), ('Emprestado', 'Emprestado'), ('Em_Uso', 'Em Uso'), ('Disponivel', 'Disponível')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoativo',
            name='status_novo',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Avariado', 'Avariado'), ('Desempossado', 'Desempossado'), ('Emprestado', 'Emprestado'), ('Em_Uso', 'Em Uso'), ('Disponivel', 'Disponível')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='instalacaosoftware',
            constraint=models.UniqueConstraint(fields=('software', 'ativo_ti'), name='uq_instalacao_software_ativo'),
        ),
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(fields=('nome', 'fabricante'), name='uq_software_nome_fabricante'),
        ),
    ]
