# Generated by Django 5.0.14 on 2026-07-07 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_remove_ativo_especificacoes_tecnicas_and_more'),
        ('instituicao', '0004_sala_sala_uq_salas_campus_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ativoti',
            name='sala',
            field=models.ForeignKey(blank=True, db_column='sala_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos_ti', to='instituicao.sala'),
        ),
        migrations.CreateModel(
            name='SolicitacaoInstalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=30)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ativo_ti', models.ForeignKey(blank=True, db_column='ativo_ti_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_instalacao', to='ativos.ativoti')),
                ('sala', models.ForeignKey(blank=True, db_column='sala_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_instalacao', to='instituicao.sala')),
                ('software', models.ForeignKey(db_column='software_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_instalacao', to='ativos.software')),
                ('solicitante', models.ForeignKey(db_column='solicitante_id', on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_instalacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Instalação',
                'verbose_name_plural': 'Solicitações de Instalações',
                'db_table': 'solicitacoes_instalacao',
            },
        ),
    ]
