# Generated by Django 5.0.14 on 2026-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_ativoti_sala_solicitacaoinstalacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Avariado', 'Avariado'), ('Desempossado', 'Desempossado')], default='Novo', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimentacaoativo',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('Novo', 'Novo'), ('Avariado', 'Avariado'), ('Desempossado', 'Desempossado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoativo',
            name='status_novo',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Avariado', 'Avariado'), ('Desempossado', 'Desempossado')], max_length=50),
        ),
    ]
