# Generated by Django 5.0.14 on 2026-07-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_ativo_emprestado_alter_ativo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='imagem_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='storage_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
